### ISSUE TITLE
Add upper bound to `errors` dependency

### ISSUE THREAD

**Issue by Gabriel439** [myfreeweb/gitson#2]
`errors-2.0` will switch to use `ExceptT` instead of `EitherT`.  If that will break your package then add an upper bound of `errors < 2.0` to your dependencies.

**Comment by Gabriel439** [comment]
Does this mean that you are already `errors-2.0` compatible?

**Comment by myfreeweb** [comment]
I guess so? Looks like I only use `hush` there too.

**Comment by Gabriel439** [comment]
Yeah, then you are `errors-2.0`-compatible.  Thanks! :)
